# Generated by Django 4.0 on 2024-04-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdate', models.DateField()),
                ('moviename', models.CharField(max_length=20)),
                ('hero', models.CharField(max_length=20)),
                ('heroine', models.CharField(max_length=20)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
